In [2]:
using CSV
using Distributions
using Plots

In [6]:
0.75*11.1+0.25*11.8

11.274999999999999

In [3]:
sum(
binomial(15,n) * 0.5^(14-k) for
k in i : j - 1

11.25

In [7]:
P(i,j,p) = sum(
binomial(14,k) * p^k * (1-p)^(14-k) for
k in i : j - 1
)

P (generic function with 1 method)

In [11]:
P(8,13,0.75)

0.8607608713209629

In [1]:
sum(
binomial(14,n) * 0.5^(14) for
n in 9 : 14
)

0.21197509765625

In [2]:
X = [6 12 8 15 7 8 12 6 10 13 11 11 10 10]

1×14 Array{Int64,2}:
 6  12  8  15  7  8  12  6  10  13  11  11  10  10

In [3]:
X = vec(X)

14-element Array{Int64,1}:
  6
 12
  8
 15
  7
  8
 12
  6
 10
 13
 11
 11
 10
 10

In [4]:
count(x->x>9, X)

9

In [5]:
D = X .- 9

14-element Array{Int64,1}:
 -3
  3
 -1
  6
 -2
 -1
  3
 -3
  1
  4
  2
  2
  1
  1

In [6]:
p = sortperm(abs.(D))

14-element Array{Int64,1}:
  3
  6
  9
 13
 14
  5
 11
 12
  1
  2
  7
  8
 10
  4

In [7]:
function rank(absD)
    len = size(absD)[1]
    rank = zeros(len)
    i = 1
    while i <= len
        if i == len
            rank[i] = i
            break
        end
        val = absD[i]
        tie = 1
        while absD[i + tie] == val
            tie += 1
        end
        rank[i:i+tie-1] .= sum(i:i+tie-1) / tie
        i += tie
    end
    return rank
end

rank (generic function with 1 method)

In [8]:
arr = [X[p] D[p] abs.(D)[p] rank(abs.(D)[p]) rank(abs.(D)[p]) .* sign.(D[p])]

14×5 Array{Float64,2}:
  8.0  -1.0  1.0   3.0   -3.0
  8.0  -1.0  1.0   3.0   -3.0
 10.0   1.0  1.0   3.0    3.0
 10.0   1.0  1.0   3.0    3.0
 10.0   1.0  1.0   3.0    3.0
  7.0  -2.0  2.0   7.0   -7.0
 11.0   2.0  2.0   7.0    7.0
 11.0   2.0  2.0   7.0    7.0
  6.0  -3.0  3.0  10.5  -10.5
 12.0   3.0  3.0  10.5   10.5
 12.0   3.0  3.0  10.5   10.5
  6.0  -3.0  3.0  10.5  -10.5
 13.0   4.0  4.0  13.0   13.0
 15.0   6.0  6.0  14.0   14.0

In [113]:
display(arr)

14×5 Array{Float64,2}:
  7.5  -0.5  0.5   1.0  -1.0
  8.7   0.7  0.7   2.0   2.0
  7.1  -0.9  0.9   3.0  -3.0
  9.2   1.2  1.2   4.0   4.0
  6.3  -1.7  1.7   5.0  -5.0
  9.8   1.8  1.8   6.0   6.0
  5.5  -2.5  2.5   7.5  -7.5
 10.5   2.5  2.5   7.5   7.5
  5.2  -2.8  2.8   9.0  -9.0
 10.9   2.9  2.9  10.0  10.0
 11.1   3.1  3.1  11.0  11.0
 11.8   3.8  3.8  12.0  12.0
 12.7   4.7  4.7  13.0  13.0
 14.4   6.4  6.4  14.0  14.0

In [9]:
display([
    "x" "d" "|d|" "r" "r±"
    arr
        ])

15×5 Array{Any,2}:
   "x"    "d"   "|d|"    "r"     "r±"
  8.0   -1.0   1.0      3.0    -3.0
  8.0   -1.0   1.0      3.0    -3.0
 10.0    1.0   1.0      3.0     3.0
 10.0    1.0   1.0      3.0     3.0
 10.0    1.0   1.0      3.0     3.0
  7.0   -2.0   2.0      7.0    -7.0
 11.0    2.0   2.0      7.0     7.0
 11.0    2.0   2.0      7.0     7.0
  6.0   -3.0   3.0     10.5   -10.5
 12.0    3.0   3.0     10.5    10.5
 12.0    3.0   3.0     10.5    10.5
  6.0   -3.0   3.0     10.5   -10.5
 13.0    4.0   4.0     13.0    13.0
 15.0    6.0   6.0     14.0    14.0

In [12]:
sum(rank(abs.(D)[p]) .* sign.(D[p]))

37.0

In [13]:
n = 14
35/
sqrt(
n*(n+1)*(2*n+1)/6
)

1.0985884360051028

In [125]:
using Statistics

In [144]:
mean(X) - 9 / (var(X) / sqrt(15))

4.660451500000938

In [130]:
var([0 2])

2.0

In [145]:
pred = 340.25
obs = [340 395 358 268]

1×4 Array{Int64,2}:
 340  395  358  268

In [146]:
q = sum((obs .- pred) .^ 2 ./ pred)

25.07788390889052

In [159]:
using CSV

In [155]:
# (a)

In [222]:
s = CSV.read("MSFT_stock.csv")[2]
x = log.(s[i] / s[i-1] for i in 2:size(s)[1])

8717-element Array{Float64,1}:
  0.03508919172532374
  0.017103186135781795
 -0.025760730735814124
 -0.017543245853564322
 -0.026905784694548112
 -0.027649769562807076
 -0.02843607191576385
  0.019046940981703255
  0.027906993414500002
  0.01818117650810043
 -0.009049269425732831
 -0.009131907082367595
  0.00913190708236767
  ⋮
  0.022530842369569027
  0.007764957603369011
 -0.010463292079081211
  0.014703715764070322
  0.010076032903392112
 -0.029955684797830232
  0.02011735957623063
 -0.02147624353162778
  0.018858489052111377
  0.0035679493280622644
  0.024532743759769757
  0.025572611488303927

In [229]:
n⁺ = count(r->r>0, x)

4391

In [227]:
# (b)

8509-element Array{Float64,1}:
  0.03508919172532374
  0.017103186135781795
 -0.025760730735814124
 -0.017543245853564322
 -0.026905784694548112
 -0.027649769562807076
 -0.02843607191576385
  0.019046940981703255
  0.027906993414500002
  0.01818117650810043
 -0.009049269425732831
 -0.009131907082367595
  0.00913190708236767
  ⋮
  0.022530842369569027
  0.007764957603369011
 -0.010463292079081211
  0.014703715764070322
  0.010076032903392112
 -0.029955684797830232
  0.02011735957623063
 -0.02147624353162778
  0.018858489052111377
  0.0035679493280622644
  0.024532743759769757
  0.025572611488303927

In [239]:
x̃ = [e for e in x if e != 0]
d̃ = x̃ .- 0
p = sortperm(abs.(d̃))

arr = [x̃[p] d̃[p] abs.(d̃)[p] rank(abs.(d̃)[p]) rank(abs.(d̃)[p]) .* sign.(d̃[p])]
display([
    "x" "d" "|d|" "r" "r±"
    arr
])

8510×5 Array{Any,2}:
   "x"           "d"          "|d|"           "r"       "r±"
  6.05202e-5    6.05202e-5   6.05202e-5      1.0       1.0
 -7.96319e-5   -7.96319e-5   7.96319e-5      2.0      -2.0
 -7.9694e-5    -7.9694e-5    7.9694e-5       3.0      -3.0
  0.000116689   0.000116689  0.000116689     4.0       4.0
  0.000116976   0.000116976  0.000116976     5.0       5.0
  0.000137343   0.000137343  0.000137343     6.0       6.0
 -0.000142247  -0.000142247  0.000142247     7.0      -7.0
  0.000142816   0.000142816  0.000142816     8.0       8.0
 -0.000144569  -0.000144569  0.000144569     9.0      -9.0
  0.000146057   0.000146057  0.000146057    10.0      10.0
 -0.00015501   -0.00015501   0.00015501     11.0     -11.0
  0.000157337   0.000157337  0.000157337    12.0      12.0
  ⋮                                                
 -0.12574      -0.12574      0.12574      8498.0   -8498.0
  0.132929      0.132929     0.132929     8499.0    8499.0
  0.146328      0.146328     0.146328   

In [236]:
k = size(x̃, 1)
t = sum(arr[:,end]) / sqrt(k * (k + 1) * (2 * k + 1) / 6)

4.3353220673529975

In [ ]:
# (c)

In [240]:
t = mean(x) / ( var(x) / sqrt(size(x, 1)) )

177.10853149085634

In [ ]:
# (d)

In [252]:
obs = [
count(r->r<-0.001, x)
count(r->-0.001<=r<-0.0004, x)
count(r->-0.0004<=r<0, x)
count(r->0<=r<0.0004, x)
count(r->0.0004<=r<0.001, x)
count(r->r>=0.001, x)
]
exp = [0.48; 0.012; 0.008] .* size(x, 1)
exp = [exp; reverse(exp)]
q = sum( (obs .- exp) .^2 ./ exp )

641.1091545256396

In [253]:
# (e)

In [257]:
x̄ = mean(x)

0.0008868566305898707

In [261]:
s² = var(x)

0.0004675170547290336

In [262]:
s = sqrt(s²)

0.02162214269514087

In [266]:
exp = [0.4651; 0.011; 0.0074;0.0074;0.0111;0.4979] .* size(x, 1)
q = sum( (obs .- exp) .^2 ./ exp )

723.0371674285628