In [14]:
using CSV
using Distributions
using Plots

In [1]:
data = [
    45 25 11 10
    68 15 8  5
    45 5  3  0
]

3×4 Array{Int64,2}:
 45  25  11  10
 68  15   8   5
 45   5   3   0

In [5]:
p = ones(1, 3) * data / sum(data)

1×4 Array{Float64,2}:
 0.658333  0.1875  0.0916667  0.0625

In [7]:
c = data * ones(4, 1)

3×1 Array{Float64,2}:
 91.0
 96.0
 53.0

In [9]:
expected = c * p

3×4 Array{Float64,2}:
 59.9083  17.0625  8.34167  5.6875
 63.2     18.0     8.8      6.0
 34.8917   9.9375  4.85833  3.3125

In [12]:
stat = (data .- expected).^2 ./ expected

3×4 Array{Float64,2}:
 3.70997   3.69254  0.847161   3.26992
 0.364557  0.5      0.0727273  0.166667
 2.92845   2.45322  0.71082    3.3125

In [13]:
stat = sum(stat)

22.02853193299814

In [3]:
X = vec(X)

14-element Array{Int64,1}:
  6
 12
  8
 15
  7
  8
 12
  6
 10
 13
 11
 11
 10
 10

In [4]:
count(x->x>9, X)

9

In [5]:
D = X .- 9

14-element Array{Int64,1}:
 -3
  3
 -1
  6
 -2
 -1
  3
 -3
  1
  4
  2
  2
  1
  1

In [6]:
p = sortperm(abs.(D))

14-element Array{Int64,1}:
  3
  6
  9
 13
 14
  5
 11
 12
  1
  2
  7
  8
 10
  4

In [7]:
function rank(absD)
    len = size(absD)[1]
    rank = zeros(len)
    i = 1
    while i <= len
        if i == len
            rank[i] = i
            break
        end
        val = absD[i]
        tie = 1
        while absD[i + tie] == val
            tie += 1
        end
        rank[i:i+tie-1] .= sum(i:i+tie-1) / tie
        i += tie
    end
    return rank
end

rank (generic function with 1 method)

In [8]:
arr = [X[p] D[p] abs.(D)[p] rank(abs.(D)[p]) rank(abs.(D)[p]) .* sign.(D[p])]

14×5 Array{Float64,2}:
  8.0  -1.0  1.0   3.0   -3.0
  8.0  -1.0  1.0   3.0   -3.0
 10.0   1.0  1.0   3.0    3.0
 10.0   1.0  1.0   3.0    3.0
 10.0   1.0  1.0   3.0    3.0
  7.0  -2.0  2.0   7.0   -7.0
 11.0   2.0  2.0   7.0    7.0
 11.0   2.0  2.0   7.0    7.0
  6.0  -3.0  3.0  10.5  -10.5
 12.0   3.0  3.0  10.5   10.5
 12.0   3.0  3.0  10.5   10.5
  6.0  -3.0  3.0  10.5  -10.5
 13.0   4.0  4.0  13.0   13.0
 15.0   6.0  6.0  14.0   14.0

In [113]:
display(arr)

14×5 Array{Float64,2}:
  7.5  -0.5  0.5   1.0  -1.0
  8.7   0.7  0.7   2.0   2.0
  7.1  -0.9  0.9   3.0  -3.0
  9.2   1.2  1.2   4.0   4.0
  6.3  -1.7  1.7   5.0  -5.0
  9.8   1.8  1.8   6.0   6.0
  5.5  -2.5  2.5   7.5  -7.5
 10.5   2.5  2.5   7.5   7.5
  5.2  -2.8  2.8   9.0  -9.0
 10.9   2.9  2.9  10.0  10.0
 11.1   3.1  3.1  11.0  11.0
 11.8   3.8  3.8  12.0  12.0
 12.7   4.7  4.7  13.0  13.0
 14.4   6.4  6.4  14.0  14.0

In [9]:
display([
    "x" "d" "|d|" "r" "r±"
    arr
        ])

15×5 Array{Any,2}:
   "x"    "d"   "|d|"    "r"     "r±"
  8.0   -1.0   1.0      3.0    -3.0
  8.0   -1.0   1.0      3.0    -3.0
 10.0    1.0   1.0      3.0     3.0
 10.0    1.0   1.0      3.0     3.0
 10.0    1.0   1.0      3.0     3.0
  7.0   -2.0   2.0      7.0    -7.0
 11.0    2.0   2.0      7.0     7.0
 11.0    2.0   2.0      7.0     7.0
  6.0   -3.0   3.0     10.5   -10.5
 12.0    3.0   3.0     10.5    10.5
 12.0    3.0   3.0     10.5    10.5
  6.0   -3.0   3.0     10.5   -10.5
 13.0    4.0   4.0     13.0    13.0
 15.0    6.0   6.0     14.0    14.0

In [12]:
sum(rank(abs.(D)[p]) .* sign.(D[p]))

37.0

In [13]:
n = 14
35/
sqrt(
n*(n+1)*(2*n+1)/6
)

1.0985884360051028

In [125]:
using Statistics

In [144]:
mean(X) - 9 / (var(X) / sqrt(15))

4.660451500000938

In [130]:
var([0 2])

2.0

In [145]:
pred = 340.25
obs = [340 395 358 268]

1×4 Array{Int64,2}:
 340  395  358  268

In [146]:
q = sum((obs .- pred) .^ 2 ./ pred)

25.07788390889052

In [31]:
using DataFrames

In [159]:
using CSV

In [155]:
# (a)

In [15]:
s = CSV.read("traffic.csv")

48204×2 DataFrame
│ Row   │ weather_main │ traffic_volume │
│       │ String       │ Int64          │
├───────┼──────────────┼────────────────┤
│ 1     │ Clouds       │ 5545           │
│ 2     │ Clouds       │ 4516           │
│ 3     │ Clouds       │ 4767           │
│ 4     │ Clouds       │ 5026           │
│ 5     │ Clouds       │ 4918           │
│ 6     │ Clear        │ 5181           │
│ 7     │ Clear        │ 5584           │
│ 8     │ Clear        │ 6015           │
│ 9     │ Clouds       │ 5791           │
│ 10    │ Clouds       │ 4770           │
⋮
│ 48194 │ Drizzle      │ 4380           │
│ 48195 │ Rain         │ 4302           │
│ 48196 │ Drizzle      │ 4302           │
│ 48197 │ Rain         │ 4283           │
│ 48198 │ Clouds       │ 4132           │
│ 48199 │ Rain         │ 3947           │
│ 48200 │ Clouds       │ 3543           │
│ 48201 │ Clouds       │ 2781           │
│ 48202 │ Thunderstorm │ 2159           │
│ 48203 │ Clouds       │ 1450           │
│ 48204 │ Clouds       │ 954            │

In [18]:
size(s)

(48204, 2)

In [25]:
clouds = [s[i,2] for i in 1:size(s,1) if s[i,1] == "Clouds"]

15164-element Array{Int64,1}:
 5545
 4516
 4767
 5026
 4918
 5791
 4770
 3539
 4623
 3591
 2898
 6292
 6057
    ⋮
  802
 1175
 2002
 2882
 3701
 4049
 4429
 4132
 3543
 2781
 1450
  954

In [26]:
clear = [s[i,2] for i in 1:size(s,1) if s[i,1] == "Clear"]

13391-element Array{Int64,1}:
 5181
 5584
 6015
 2784
 2361
 1529
  963
  506
  321
  273
  367
  814
 2718
    ⋮
 5798
 4791
 4574
 3544
  867
  524
  359
  425
  743
 1359
 2036
 4059

In [27]:
snow = [s[i,2] for i in 1:size(s,1) if s[i,1] == "Snow"]

2876-element Array{Int64,1}:
 5234
 4695
 5341
 5943
 5874
 5879
 6060
 4771
 2067
  671
 4245
 4148
 2222
    ⋮
  357
  779
 2238
 4364
 4963
 4463
 3860
 4149
 4824
 5013
 7022
 6459

In [41]:
series = [[clouds]; [clear]; [snow]]

3-element Array{Array{Int64,1},1}:
 [5545, 4516, 4767, 5026, 4918, 5791, 4770, 3539, 4623, 3591  …  2002, 2882, 3701, 4049, 4429, 4132, 3543, 2781, 1450, 954]
 [5181, 5584, 6015, 2784, 2361, 1529, 963, 506, 321, 273  …  4574, 3544, 867, 524, 359, 425, 743, 1359, 2036, 4059]
 [5234, 4695, 5341, 5943, 5874, 5879, 6060, 4771, 2067, 671  …  2238, 4364, 4963, 4463, 3860, 4149, 4824, 5013, 7022, 6459]

In [56]:
series = [[clouds]; [clear]; [snow]]
rows = [[1:length(s);] for s in series]
df = flatten(DataFrame(g=["Clouds","Clear","Snow"], s=series, r=rows), [:s, :r])
df = unstack(df, :g, :s)[:,2:end]

15164×3 DataFrame
│ Row   │ Clear   │ Clouds │ Snow    │
│       │ Int64?  │ Int64? │ Int64?  │
├───────┼─────────┼────────┼─────────┤
│ 1     │ 5181    │ 5545   │ 5234    │
│ 2     │ 5584    │ 4516   │ 4695    │
│ 3     │ 6015    │ 4767   │ 5341    │
│ 4     │ 2784    │ 5026   │ 5943    │
│ 5     │ 2361    │ 4918   │ 5874    │
│ 6     │ 1529    │ 5791   │ 5879    │
│ 7     │ 963     │ 4770   │ 6060    │
│ 8     │ 506     │ 3539   │ 4771    │
│ 9     │ 321     │ 4623   │ 2067    │
│ 10    │ 273     │ 3591   │ 671     │
⋮
│ 15154 │ missing │ 1175   │ missing │
│ 15155 │ missing │ 2002   │ missing │
│ 15156 │ missing │ 2882   │ missing │
│ 15157 │ missing │ 3701   │ missing │
│ 15158 │ missing │ 4049   │ missing │
│ 15159 │ missing │ 4429   │ missing │
│ 15160 │ missing │ 4132   │ missing │
│ 15161 │ missing │ 3543   │ missing │
│ 15162 │ missing │ 2781   │ missing │
│ 15163 │ missing │ 1450   │ missing │
│ 15164 │ missing │ 954    │ missing │

In [58]:
CSV.write("df.csv", df)

"df.csv"

In [227]:
# (b)

8509-element Array{Float64,1}:
  0.03508919172532374
  0.017103186135781795
 -0.025760730735814124
 -0.017543245853564322
 -0.026905784694548112
 -0.027649769562807076
 -0.02843607191576385
  0.019046940981703255
  0.027906993414500002
  0.01818117650810043
 -0.009049269425732831
 -0.009131907082367595
  0.00913190708236767
  ⋮
  0.022530842369569027
  0.007764957603369011
 -0.010463292079081211
  0.014703715764070322
  0.010076032903392112
 -0.029955684797830232
  0.02011735957623063
 -0.02147624353162778
  0.018858489052111377
  0.0035679493280622644
  0.024532743759769757
  0.025572611488303927

In [93]:
ss(vec, m) = sum((vec .- m).^2)

ss (generic function with 1 method)

In [131]:
x = [
709 659 713 726 660 645
668 685 722 740 692 720
659 685 666 684 678 750
698 650 704 666 686 733]

# m = x * 
# [
#     1 1 0 0 0 0
#     0 0 1 1 0 0
#     0 0 0 0 1 1
# ]' ./ 2 * 
# [
#     1 1 0 0 0 0
#     0 0 1 1 0 0
#     0 0 0 0 1 1
# ]

mu = sum(x) 

# ss(x, mu)

16598

In [81]:
for i in x
    println("\\overset{", i, "}{")
end

\overset{684.0}{
\overset{676.5}{
\overset{672.0}{
\overset{674.0}{
\overset{719.5}{
\overset{731.0}{
\overset{675.0}{
\overset{685.0}{
\overset{652.5}{
\overset{706.0}{
\overset{714.0}{
\overset{709.5}{


In [239]:
x̃ = [e for e in x if e != 0]
d̃ = x̃ .- 0
p = sortperm(abs.(d̃))

arr = [x̃[p] d̃[p] abs.(d̃)[p] rank(abs.(d̃)[p]) rank(abs.(d̃)[p]) .* sign.(d̃[p])]
display([
    "x" "d" "|d|" "r" "r±"
    arr
])

8510×5 Array{Any,2}:
   "x"           "d"          "|d|"           "r"       "r±"
  6.05202e-5    6.05202e-5   6.05202e-5      1.0       1.0
 -7.96319e-5   -7.96319e-5   7.96319e-5      2.0      -2.0
 -7.9694e-5    -7.9694e-5    7.9694e-5       3.0      -3.0
  0.000116689   0.000116689  0.000116689     4.0       4.0
  0.000116976   0.000116976  0.000116976     5.0       5.0
  0.000137343   0.000137343  0.000137343     6.0       6.0
 -0.000142247  -0.000142247  0.000142247     7.0      -7.0
  0.000142816   0.000142816  0.000142816     8.0       8.0
 -0.000144569  -0.000144569  0.000144569     9.0      -9.0
  0.000146057   0.000146057  0.000146057    10.0      10.0
 -0.00015501   -0.00015501   0.00015501     11.0     -11.0
  0.000157337   0.000157337  0.000157337    12.0      12.0
  ⋮                                                
 -0.12574      -0.12574      0.12574      8498.0   -8498.0
  0.132929      0.132929     0.132929     8499.0    8499.0
  0.146328      0.146328     0.146328   

In [236]:
k = size(x̃, 1)
t = sum(arr[:,end]) / sqrt(k * (k + 1) * (2 * k + 1) / 6)

4.3353220673529975

In [ ]:
# (c)

In [240]:
t = mean(x) / ( var(x) / sqrt(size(x, 1)) )

177.10853149085634

In [ ]:
# (d)

In [252]:
obs = [
count(r->r<-0.001, x)
count(r->-0.001<=r<-0.0004, x)
count(r->-0.0004<=r<0, x)
count(r->0<=r<0.0004, x)
count(r->0.0004<=r<0.001, x)
count(r->r>=0.001, x)
]
exp = [0.48; 0.012; 0.008] .* size(x, 1)
exp = [exp; reverse(exp)]
q = sum( (obs .- exp) .^2 ./ exp )

641.1091545256396

In [253]:
# (e)

In [257]:
x̄ = mean(x)

0.0008868566305898707

In [261]:
s² = var(x)

0.0004675170547290336

In [262]:
s = sqrt(s²)

0.02162214269514087

In [266]:
exp = [0.4651; 0.011; 0.0074;0.0074;0.0111;0.4979] .* size(x, 1)
q = sum( (obs .- exp) .^2 ./ exp )

723.0371674285628